### ISSUE TITLE
step2 failed due to Docker update

### ISSUE THREAD

**Issue by vager** [EMCECS/ECS-CommunityEdition#465] opened 2019-04-10 10:44 UTC
### Expected Behavior
step2 success

### Actual Behavior
(Please put additional output and logs in the section for that below)
```
> Pinging Management API Endpoint until ready
> Pinging endpoint 172.16.3.14... (CTRL-C to break)
> PONG: api_endpoint=172.16.3.14 username=root diag_endpoint=172.16.3.14 dt_total=0 dt_unready=0 dt_unknown=0

> Creating Storage Pool: vdc1/sp1
>       OK
> Adding Data Stores to Storage Pool:
>       vdc1/sp1/172.16.3.14
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 629, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/bin/ecsconfig.py", line 606, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 187, in _request
    raise ECSClientException(message=msg)
ecsclient.common.exceptions.ECSClientException: Request error: (ReadTimeoutError("HTTPSConnectionPool(host='172.16.3.14', port=4443): Read timed out. (read timeout=300)",),)
```
### Steps to Reproduce Behavior
1. install latest Centos7 minimal on KVM
2. ./bootstrap.sh -y -g -c deploy.yml
3. reboot
4. step1
5. step2

### Relevant Output and Logs
```
[root@luna ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@luna ~]# 
[root@luna ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@luna ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Tue Mar 12 10:27:24 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Tue Mar 12 10:27:24 2019
 OS/Arch:         linux/amd64
 Experimental:    false
[root@luna ~]# 
[root@luna ~]# docker image ls
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/emccorp/ecs-install          latest              95cbbbffd233        3 weeks ago         165 MB
emccorp/ecs-install                    latest              95cbbbffd233        3 weeks ago         165 MB
docker.io/emccorp/ecs-software-3.2.2   3.2.2.0             a18ba091d4f3        7 months ago        1.73 GB
emccorp/ecs-software                   latest              a18ba091d4f3        7 months ago        1.73 GB
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by captntuttle** [comment] 2019-04-15 19:03
Looking into this. Can reproduce.

This is really strange, nothing has changed.

**Comment by Lupi619** [comment] 2019-04-16 16:10
This has been an issue for awhile.  Also happened to me using the ova.  Which the ova link seems to also be down at the momment of writing this.

**Comment by captntuttle** [comment] 2019-04-16 17:53
Yes, the OVA link is down due to an outage with the host. We're working on a solution to that.

@Lupi619 do you know about how long this issue has been around? I'm trying to track where this broke.

**Comment by captntuttle** [comment] 2019-04-16 18:54
Ok, this issue is caused by a Docker update that appears to be severely limiting the number of forks the container can execute. This issue is resolved by versionlocking an earlier Docker build. 

`docker-1.13.1-75.git8633870.el7.centos` is proven to work but I am still determining the latest working build.

**Comment by Lupi619** [comment] 2019-04-16 20:15
Ok, thanks for the update on the link.
I want to say this happened to me backin November time frame.  I actually just manually setup what I needed and skipped step 2.  When I went to build this on a base CentOS I couldn't even get step1 to work.  So that is why I've leaned on the ova.  Not sure if the docker issue has to do with that as well.  Although since it was months ago I do not remember the errors.  If the ova link is not back up in a few days I will have to test this again anyways.

**Comment by zeljkosu** [comment] 2019-04-17 10:54
Thank you for this (docker-1.13.1-75.git8633870.el7.centos)... Succesfully installed just now :)

**Comment by captntuttle** [comment] 2019-04-18 18:21
For the sake of record, until I make a permanent solution, the workaround is:

1) install versionlock
`sudo yum install yum-versionlock -y`

2) install previous working docker build (you may have to uninstall docker first)
`sudo yum install docker-1.13.1-75.git8633870.el7.centos -y`

3) version lock docker 
`sudo yum versionlock docker docker-client docker-common`

**Comment by California-CSE** [comment] 2019-04-24 18:48
@vager -- perhaps changing the title to read "Step 2 failed due to Docker update" may help others

**Closed** 2020-01-03 20:12 UTC
