### ISSUE TITLE
Can not login ECS 3.2.0.0 via WebUI  after some time. 

### ISSUE THREAD

**Issue by cdnyyzyul** [EMCECS/ECS-CommunityEdition#424] opened 2018-05-15 13:54 UTC
### Actual Behavior
deployed dellemc-ecsce-3.2.0.0-install-node-2.7.0-vm0.ova, installed ESC on single VM. Then I was able to log in https://<hostname> with root/ChangeMe and change the password. Login again with the new password. 

But, the next day, it does not allow me to login any more.
The first time I run into this problem, I reinstalled the ECS. 
But I could not login again the next day. 

![capture-ecs32-login](https://user-images.githubusercontent.com/39199903/40060600-fff0128c-5824-11e8-9885-5ae851026461.PNG)

### Steps to Reproduce Behavior

1. deploy dellemc-ecsce-3.2.0.0-install-node-2.7.0-vm0.ova, install ECS on the install-node
2. login WebUI, change password for root, continue configure the ECS. Repeat to Logout, login several times, all good.
3. the next day (I don't know how long exactly), login WebUI fails.

### Relevant Output and Logs
see attached image.

# Output and Logs go here
I will provide any required logs.

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment] 2018-05-22 14:51
This often occurs when the ECS services run out of a resource and fail.  Deployments are often much more stable after providing them with more than the minimum required resources to bootstrap.  Our recommended deployment resources can be found here: https://github.com/EMCECS/ECS-CommunityEdition#recommended

**Comment by Beowulf67** [comment] 2018-05-24 13:57
Hi
I have the same issue with a simular environment then stefanff. (four-node ECS 3.2.0.0 OVA deployment)
It is not possible to login anymore.
Can someone drop the way to check which services are running?
Please step by step as not all are Linux or Unix Specialists.

What should we check to get deeper into the issues?
Please can you drop us the way to get to the required logfiles.

**Comment by holgerjakob** [comment] 2018-05-24 14:12
Hi all
Same behavior for me as well. And our vms run with 48GB of Memory, 8 Processors and 500GB sdb volumes. Four machines in the clusters. The same for both of the vdcs

**Comment by stefanff** [comment] 2018-05-24 17:10
Hi Beowulf67, in order to check the running services you can attach to the ECS container using
# nsenter -i -m -p -u -t `pidof blobsvc`
and then run 
# service -s
The thing is that today I re-deployed the ECS, the WebUI works fine for the moment, but there is still no authsvc running in the container. So, it seems that not seing authsvc in the list is not relevant to this issue. I wonder why WebUI is even working now.

**Comment by stefanff** [comment] 2018-05-24 17:17
I meant
nsenter -i -m -p -u -t \`pidof blobsvc\`

**Comment by robinbohm** [comment] 2018-05-25 08:58
Some problem for me. After a day or so can not logon to the ECS 3.2.0.0 OVA management page. Furthermore the storage is automagically filling. 247 GB filled of 580 GB attached after half a day and not a single file writtten by me because connect to S3 with Cyberduck does'nt work. Resources plenty.
This is not exactly promotion for the product. Maybe I should check with pre-sales for the complete package or skip to HCP or COS.

**Comment by padthaitofuhot** [comment] 2018-05-25 13:51
We've seen this in a few other deployments.  I'm currently researching the issue and resolving this is my highest priority task at the moment.  I'll post updates to this issue thread.

**Comment by padthaitofuhot** [comment] 2018-05-25 16:37
Hello all.  I still haven't been able to replicate this failure in my lab, despite several reported instances.  It's possible the loads I'm driving aren't similar to those encountered by ECS when it fails.  Could you all update this ticket with a description of how you're using ECS CE prior to failure?  I'd like to see if I can't track this issue down before the end of the day.

**Comment by cdnyyzyul** [comment] 2018-05-25 17:09
I built the ECS for testing Data Domain cloud tier. There is really no load in my environment when I run into the problem.
The first time, The ECS 3.2 is up, I only created an object user. It was left ideal until I found that I could not login.
After reinstalled ECS 3.2, configured Data Domain to access it. It was left ideal over night. Then run into this login problem again. 

Now, I am running ECS 3.1.

**Comment by UdjatMiner** [comment] 2018-05-25 18:50
Did others having the issue set a static IP?  I did a test deployment with the OVA, set static IP, ran videploy, step1, step2, wait and then login to WebUI fine.  Leave overnight (6-8 hours) and can no longer login to WebUI.  I am now going to re-test and leave it using DHCP.

**Comment by stefanff** [comment] 2018-05-26 21:05
I used static IP too. There was no activity prior to failure. I only got to create one CAS bucket and an object user. After a couple of days used jcasscript to write to the bucket, succesfully connected to the pool, but the write failed. While investigating the write problem I discovered I could no longer log into WebUI.

**Comment by NASMAN5000** [comment] 2018-05-27 15:10
I asked about static IP because I was looking for something unique, but there is no relation.  The screenshot below is the last one I captured, taken about 10 hours after OVA deployment and 1 bucket creation.  I used the default OVA storage (104GB), changed the memory from 2GB to 16GB, and DHCP for network. (Everything here also verified with static IP.)  
It has now been 23 hours total.  I cannot login to the WebUI.  All I did was configure and leave it idle.  No client activity.  The pool filled to capacity in approx. 9 hours.  I am not sure if this is normal.  For example, if the pool capacity is assigned to the bucket capacity, and therefor considered used by pool.  I am new to working with ECS.
I can still login via SSH if anyone wants me to run some commands and/or capture logs.  If so, I need some guidance on what exactly needs to be done. 
![snag-0373](https://user-images.githubusercontent.com/8305025/40587464-dfbb7532-6194-11e8-99bf-5ae1fad90c0d.png)

WebUI login attempt shows the following.
![snag-0375](https://user-images.githubusercontent.com/8305025/40587550-189a8a04-6196-11e8-8d60-b5c8c5203abd.png)

**Comment by padthaitofuhot** [comment] 2018-05-29 17:44
So, I haven't been able to duplicate any of these issues with the ECS 3.2.0.1 release in my labs.  I recommend updating to ECS CE 2.7.2 and retrying.  I am currently generating the OVA for 2.7.2 and will notify this issue as soon as it is generated and available online.  Please let me know if you continue to see these issues with the 3.2.0.1 release of ECS,

**Comment by padthaitofuhot** [comment] 2018-05-29 19:50
The OVA for 2.7.2/3.2.0.1 has been put online: http://130852476153187606.public.ecstestdrive.com/public/dellemc-ecsce-3.2.0.1-install-node-2.7.2-vm0.ova

**Comment by stefanff** [comment] 2018-05-30 08:38
Tried to download the OVA for 3.2.0.1 but it constantly fails at 355MB. Can you please double check the repository?

**Comment by NASMAN5000** [comment] 2018-05-30 12:37
The new build, 3.2.0.1/2.7.2, shows similar behavior.  The new VM has been running for 13 hours.  I can still login to WebUI, so far.   However, the pool is still filling up by itself.  I suspect I will be locked out from WebUI in a few hours.

![image](https://user-images.githubusercontent.com/8305025/40720389-2b21fa2a-63dc-11e8-878c-32af4bfdde0d.png)

**Comment by padthaitofuhot** [comment] 2018-05-30 15:42
@holgerjakob Alright, well if you zip your /var/log/vipr directory up from the node on which you were attempting to access the management portal, and attach them somehow to a reply, then we can take a look and see what's falling over.

**Comment by NASMAN5000** [comment] 2018-05-30 16:04
@padthaitofuhot - I understand your points, however my 3.1.0.3 deployment has the same capacity (OVA default) and has been running for a couple weeks without issue.  The 3.1.0.3 instances still has ~30GB available.  If you need more logs, I can collect them as well.

**Comment by padthaitofuhot** [comment] 2018-05-30 16:31
@NASMAN5000 yes, absolutely I'd like to see logs from the failing 3.2.0.1 instance.  To be clear, it shouldn't just up and fall over.  On the node where the management portal is failing, please zip your /var/log/vipr directory up and send me either a link or directly attach the files to this thread (if possible, I'm not sure what the size limits are for direct attachments).  Thanks!

**Comment by holgerjakob** [comment] 2018-05-30 16:43
Hi all
The files I was able to get are available at
https://s3-swiss.s3target.com/websharing/vipr.zip?AWSAccessKeyId=00a3286083d21320472a&Expires=1529964000&Signature=itKFCOiaNokROWWfTaucw9GGiC0%3D&x-amz-pt=ODIxMmM2MzgyMTUyNzY5ODU1NzgxNw
Best regards, Holger

**Comment by padthaitofuhot** [comment] 2018-05-30 20:59
Hey All, we have a lead on a possible cause and are pursuing it.  I'll update within 24 hours with a status report.  Thank you for reporting this issue and having patience while it's sorted out.

**Comment by padthaitofuhot** [comment] 2018-05-31 19:45
Okay, I'm currently working on a patch to the tuning parameters for a service within ECS that is running out of memory and restarting frequently.  I won't have an OVA delivered for the patch until probably next week, although I may have time tomorrow to get it built.  No promises though.  Until then, once I get the patch pushed to the master branch of this repo, you will be able to get the new code if you're willing to build an install node from a minimal CentOS 7.5 image.  Docs are available from the main README.md.  Once again, thank you for your contributions and patience.

**Comment by padthaitofuhot** [comment] 2018-05-31 23:20
This should be resolved by #433.  I haven't seen any CM restarts over the past hour.  Please let me know if you're still seeing storage consumption increment over time.

**Comment by auchiau** [comment] 2018-06-01 08:40
I'm having the same issue, couldn't login to WebUI on the next day of deployment of ECS VM. My ova file is dellemc-ecsce-3.2.0.0-install-node-2.7.0-vm0.ova and I believe the ECS version should be 3.2.0.0. We are waiting for the patch or a confirmed version that this issue would be fixed. Thanks a lot.

**Comment by padthaitofuhot** [comment] 2018-06-01 13:03
@auchiau Please see this comment: https://github.com/EMCECS/ECS-CommunityEdition/issues/424#issuecomment-393656271

**Comment by padthaitofuhot** [comment] 2018-06-04 19:32
All - It appears that while the changes made did in fact help, they haven't fully resolved the issue.  We're continuing to look at the issue and will update again as soon as we find the cause of orphaned chunks.

**Comment by bonescs** [comment] 2018-06-05 12:37
I'm having the same issue with ECS 3.2.0.0 OVA. 
SSH into VM works, GUI don't work anymore. 
As additional information I can say following regarding used-space from GUI before I couldn't login anymore:
- Userdata 2 GB
- System Metadata 90 GB
- Protection overhead 183 GB

And I've uploaded around max. 1-2 GB of data.

**Comment by padthaitofuhot** [comment] 2018-06-06 14:04
We've released ECS CE 2.8.0 for ECS 3.2.0.1.  https://github.com/EMCECS/ECS-CommunityEdition/releases/tag/2.8.0-3.2.0.1

This issue should be resolved, as well as some other issues that were masked by the original issue.  In any event, the Web UI should remain online for the duration of the ECS VM.  Please let us know if you continue to have issues with the Web UI stopping.

**Comment by padthaitofuhot** [comment] 2018-06-07 20:30
Closing this issue.  Please reopen if you encounter this issue again.  Thank you.

**Closed by padthaitofuhot** 2018-06-07 20:30 UTC
Labels: Major, bug, pending close

**Comment by Lupi619** [comment] 2019-08-21 14:49
Is there a work around for this, besides deploying a new version?  I am currently facing this issue with ECS 3.2.0.1 and would prefer to fix the current version before having to deploy a new one.
