### ISSUE TITLE
Error adding node to a storage pool

### ISSUE THREAD

**Issue by pveredas** [EMCECS/ECS-CommunityEdition#305] opened 2017-07-04 12:47 UTC
Can not create StoragePool on a newly vapp image installed ECS-CE, recieve the following error:
 
Error 1013 (http: 400): Bad request body. Error while registering 1 commodity nodes

Please help

Paulo

**Comment by pveredas** [comment] 2017-07-04 12:50
to complement:
> Adding Data Stores to Storage Pool:
> 	vdc1/sp1/10.80.161.154
Traceback (most recent call last):
  File "/usr/local/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.0.3', 'console_scripts', 'ecsconfig')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/ecsconfig.py", line 627, in sp
    tasks = add_all()
  File "/usr/local/bin/ecsconfig.py", line 603, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/local/bin/ecsconfig.py", line 595, in add_one
    sp_tasks.append(sp_add_node(sp_id, node))
  File "/usr/local/bin/ecsconfig.py", line 572, in sp_add_node
    return conf.api_client.data_store.create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/common/provisioning/data_store.py", line 217, in create
    return self.conn.post('vdc/data-stores/commodity', json_payload=payload)
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/local/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Error while registering 1 commodity nodes - Bad request body: https://10.80.161.154:4443/vdc/data-stores/commodity 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo
>

**Comment by adrianmo** [comment] 2017-07-05 12:41
@pveredas Thanks for reporting the error. We also experienced the error you described and identified an issue in the latest release. 

We have already updated the upstream binaries so you should be able to deploy ECS CE successfully.

Please let us know how it goes.

Thanks,
-Adrian

**Comment by padthaitofuhot** [comment] 2017-07-05 16:54
Which branch (master or develop) are you seeing this issue in?

**Comment by pveredas** [comment] 2017-07-06 16:41
Thanks,

I was able to install it but have the following issue:

![image](https://user-images.githubusercontent.com/29892584/27922162-0b2e8b00-6272-11e7-8d24-940e81d63038.png)

The storage pool is still initializing/Not Ready but I'm able to upload and download files from a test bucket..

Any idea?
Paulo Veredas

**Comment by padthaitofuhot** [comment] 2017-07-06 16:44
The persistent “initializing/not ready” thing is a display bug and purely cosmetic.  No ECS CE functionality is affected by that issue.

**Comment by padthaitofuhot** [comment] 2017-07-12 22:51
Caused by #301

**Comment by padthaitofuhot** [comment] 2017-07-12 22:52
Resolved by #309

**Closed by padthaitofuhot** 2017-07-12 22:52 UTC
Labels: Major, upstream
